import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styles from "../../src/styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>NOLAN MARKET</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.navbar}>
        <ConnectButton
          chainStatus={{
            smallScreen: "icon",
            largeScreen: "full",
          }}
          accountStatus={{
            smallScreen: "avatar",
            largeScreen: "full",
          }}
        />
      </div>
          <ul>
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link href="/create">Create</Link>
            </li>
            <li>
              <Link href="/market">Marketplace</Link>
            </li>
            <li>
              <Link href="/wallet">Wallet</Link>
            </li>
          </ul>
      
    </div>
  );
};

export default Home;
